CREATE DATABASE resort;
USE resort;


CREATE TABLE User (
	user_ID INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) UNIQUE NOT NULL
);


CREATE TABLE Trash (
	trash_ID INT PRIMARY KEY,
    t_material VARCHAR(255) NOT NULL
);


CREATE TABLE Recycle (
	recycle_ID INT PRIMARY KEY,
    r_material VARCHAR(255) NOT NULL
);


CREATE TABLE Compost (
	compost_ID INT PRIMARY KEY,
    c_material VARCHAR(255) NOT NULL
);


CREATE TABLE Sorted (
	user_ID INT,
	trash_ID INT,
    recycle_ID INT,
    compost_ID INT,
	PRIMARY KEY (user_ID),
	FOREIGN KEY (user_ID) REFERENCES User(user_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (trash_ID) REFERENCES Trash(trash_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (recycle_ID) REFERENCES Recycle(recycle_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (compost_ID) REFERENCES Compost(compost_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE User
ADD email varchar(255);

ALTER TABLE Sorted DROP FOREIGN KEY sorted_ibfk_1;  -- For user_ID
ALTER TABLE Sorted DROP FOREIGN KEY sorted_ibfk_2;  -- For trash_ID
ALTER TABLE Sorted DROP FOREIGN KEY sorted_ibfk_3;  -- For recycle_ID
ALTER TABLE Sorted DROP FOREIGN KEY sorted_ibfk_4;  -- For compost_ID

ALTER TABLE Trash MODIFY trash_ID INT AUTO_INCREMENT;
ALTER TABLE Recycle MODIFY recycle_ID INT AUTO_INCREMENT;
ALTER TABLE Compost MODIFY compost_ID INT AUTO_INCREMENT;

ALTER TABLE Trash DROP COLUMN user_id;
ALTER TABLE Recycle DROP COLUMN user_id;
ALTER TABLE Compost DROP COLUMN user_id;


CREATE TABLE SortingHistory (
	history_id INT AUTO_INCREMENT PRIMARY KEY,
	user_id int,
	item VARCHAR(255) NOT NULL,
	disposal_method ENUM('trash', 'recycle', 'compost') NOT NULL,
	sort_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES User(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE Trash ADD COLUMN user_id INT;
ALTER TABLE Trash ADD FOREIGN KEY (user_id) REFERENCES User(user_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Recycle ADD COLUMN user_id INT;
ALTER TABLE Recycle ADD FOREIGN KEY (user_id) REFERENCES User(user_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE Compost ADD COLUMN user_id INT;
ALTER TABLE Compost ADD FOREIGN KEY (user_id) REFERENCES User(user_ID) ON UPDATE CASCADE ON DELETE CASCADE;



