CREATE DATABASE resort;
USE resort;

CREATE TABLE User (
	user_ID INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Trash (
	trash_ID INT PRIMARY KEY,
    t_material VARCHAR(255) NOT NULL
);

CREATE TABLE Recycle (
	recycle_ID INT PRIMARY KEY,
    r_material VARCHAR(255) NOT NULL
);

CREATE TABLE Compost (
	compost_ID INT PRIMARY KEY,
    c_material VARCHAR(255) NOT NULL
);

CREATE TABLE Sorted (
	user_ID INT,
	trash_ID INT,
    recycle_ID INT,
    compost_ID INT,
	PRIMARY KEY (user_ID),
	FOREIGN KEY (user_ID) REFERENCES User(user_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (trash_ID) REFERENCES Trash(trash_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (recycle_ID) REFERENCES Recycle(recycle_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (compost_ID) REFERENCES Compost(compost_ID) ON UPDATE CASCADE ON DELETE CASCADE
);